name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: setup
      run: | 
        sudo apt-get update -qq
        sudo apt-get install gcc-multilib
        sudo apt-get install -y --no-install-recommends cmake make libglfw3 libglfw3-dev libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxfixes-dev
    - name: build environment
      run: cmake -E make_directory ${{github.workspace}}/build
    - name: configure
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake -B . -S ../src
    - name: build
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config Release
